### ISSUE TITLE
Tests Sometimes Fail

### ISSUE THREAD

**Issue by axdg** [raywhite/async-hofs#10]
Given the nature of the module, a couple of the tests rely on timers... and if for whatever reason the event loop can't fire `setTimeout`s callback at the expected time (and / or some assertion runs slightly too early / late), several tests will fail.

It's not ideal for tests to rely on side effects, AFAIK there's no way around it. The best solution is probably to just increase the tolerance / decrease precision of tests that rely on `setTimeout`, and not rely on `setTimeout` / `sleep` unless absolutely necessary.

NOTE: The main culprits are `benchmark` and `memoize`.

**Comment by elyobo** [comment]
Had similar problems with the caching system in the office sites, which has a similar sort of idea (but offers multiple back ends for the same cache wrapper in order to support server side caching through redis and client side caching through localforage).  There's a limit to how accurate `setTimeout` actually is, so you just can't cut it too fine.

**Comment by elyobo** [comment]
> RPC (stdin / stdout) from some child process (tests in different files), blocking the setTimeout callbacks from fireing

That's a thing?

It sounds like 1 would be impossible to fix totally, so 2 is probably better, but 3) stopping whatever is somehow stopping setTimeout from firing would be better still.

**Comment by axdg** [comment]
> That's a thing?

Yeah, each test file runs in a seperate process in ava... so RPC is done through `stdin / out`, the listeners are one of the things that could be blocking the thread with the timeout from fireing a callback at a reasonable time.

And then also, there are the other tests in the same file. AFAIK `setTimout` will never fire a callback early... so it's things it's things like the above, or sync work (from tests in the same file) happening right before a timeout is "meant" to fire and blocking it that would be the problem.

Given that, options 3 and 2 are kind of the same thing... don't do things concurrently.

**Comment by elyobo** [comment]
But... Each test is running in a single process and isn't dependant on the
RPC, so I don't get why it has any impact. And presumably each process is
only running one test at a time so you shouldn't really be doing anything
much at the same time to block it...

Yes, setTimeout is a minimum not a maximum, true. It should still be
possible to have it work with sane tolerances. I think.

**Comment by axdg** [comment]
I think I fixed this with some really liberal timing and decreasing test concurrency (a while ago).

Closing.
